### ISSUE TITLE
time consuming to render

### ISSUE THREAD

**Issue by huangyuan2020** [SangHunHan92/2K2K#5]
Thanks a lot for your work! I have a question about the time consuming to render. 
"It takes about 2-3 days to render a 2048×2048 resolution images" whether means to render a group of image and depth for one obj file, it may task 2-3 days?

**Comment by SangHunHan92** [comment]
![2023-07-28 17-08-54](https://github.com/SangHunHan92/2K2K/assets/38457117/880a08f1-b174-4d3c-83d2-19e475c7cf55)

In my setup, it takes 50s per one mesh(obj), which can render about 1,800 meshes in a day.
However, I said 2~3 days because it could take longer depending on the degree of rendering angles and CPU spec.
